replicaCount: 1

# The tag line below is rewritten by the update_config pipeline stage.
image:
  repository: registry.gitlab.com/CHANGE_ME_GL_USER/training-app/trainingcicd
  tag: "0.0.1-SNAPSHOT"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
