apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: projectfortrainingbe-chart
  namespace: flux-system
spec:
  interval: 10m
  url: https://gitlab.com/CHANGE_ME_GL_USER/training-config.git
  ref:
    branch: main
  # Credentials created by "flux bootstrap gitlab --token-auth"
  secretRef:
    name: flux-system
