apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: projectfortrainingbe-chart
  namespace: flux-system
spec:
  interval: 10m
  releaseName: projectfortrainingbe-chart
  targetNamespace: trainingcicd
  storageNamespace: trainingcicd
  timeout: 3m
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/projectfortrainingbe-chart
      # Revision: repackage the chart on every Git revision, so changes in values.yaml
      # (the image tag written by CI) are picked up without bumping the chart version.
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: projectfortrainingbe-chart
        namespace: flux-system
